### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#8]
Hi there,

I am in a weird situation. I have two tests, `TestDKGProtocol` and `TestMarshalling`. The first one test the DKG protocol with the BLS library, and the other one test the (un)marshalling functionalities in parallel.
When I run both independantly, with `go test -v -run TestDKGProtocol` for example, it works fine. But when I run the both consecutively, with `go test -v `, it fails with a seg fault in the C library call. The first one is `TestDKGProtocol` and the second one is `TestMarshalling`.
Here is the head of my log:
```
=== RUN   TestDkgProtocol
2 : (                protocol.TestDkgProtocol:  28) - Running dkg with 5 hosts
--- PASS: TestDkgProtocol (0.52s)
=== RUN   TestMarshallingPoint
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x89433a, 0x2a)
	/usr/lib/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 41 [syscall, locked to thread]:
runtime.cgocall(0x79f0c0, 0xc4202a9238, 0x8938b1)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4202a91f8 sp=0xc4202a91b8
github.com/dfinity/go-dfinity-crypto/bls._Cfunc_mclBnG2_deserialize(0xc4202c3680, 0xc4200c037f, 0x60, 0x0)
	github.com/dfinity/go-dfinity-crypto/bls/_obj/_cgo_gotypes.go:748 +0x4d fp=0xc4202a9238 sp=0xc4202a91f8
github.com/dfinity/go-dfinity-crypto/bls.(*G2).Deserialize.func1(0xc4200c037f, 0x60, 0x100, 0xc4202c3680, 0xc4200c037f, 0x60, 0xc4202a92f0)
	/home/nalos/prog/go/src/github.com/dfinity/go-dfinity-crypto/bls/mcl.go:332 +0xed fp=0xc4202a9290 sp=0xc4202a9238
github.com/dfinity/go-dfinity-crypto/bls.(*G2).Deserialize(0xc4202c3680, 0xc4200c037f, 0x60, 0x100, 0x0, 0x0)
	/home/nalos/prog/go/src/github.com/dfinity/go-dfinity-crypto/bls/mcl.go:332 +0x66 fp=0xc4202a9300 sp=0xc4202a9290
github.com/dedis/paper_17_dfinity/pbc.(*pointG2).UnmarshalBinary(0xc4202c3680, 0xc4200c037f, 0x60, 0x100, 0x496485d291cc1db1, 0xd6d62d8d35b660cf)
	/home/nalos/prog/go/src/github.com/dedis/paper_17_dfinity/pbc/point.go:193 +0x4b fp=0xc4202a9340 sp=0xc4202a9300
....
```
One time the error occurs in `mclBnG2_deserialize()` and the other time (like half of the time), the error occurs in `mclBnG2_HashAndMapTo`.
```
goroutine 84 [syscall, locked to thread]:
runtime.cgocall(0x79f1a0, 0xc420487220, 0x89391c)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4204871e0 sp=0xc4204871a0
github.com/dfinity/go-dfinity-crypto/bls._Cfunc_mclBnG2_hashAndMapTo(0xc4203843c0, 0xc4204d1380, 0x184, 0x0)
	github.com/dfinity/go-dfinity-crypto/bls/_obj/_cgo_gotypes.go:779 +0x4d fp=0xc420487220 sp=0xc4204871e0
github.com/dfinity/go-dfinity-crypto/bls.(*G2).HashAndMapTo.func1(0xc4204d1380, 0x184, 0x1a0, 0xc4203843c0, 0xc4204d1380, 0x184, 0x1a0)
	/home/nalos/prog/go/src/github.com/dfinity/go-dfinity-crypto/bls/mcl.go:352 +0xed fp=0xc420487278 sp=0xc420487220
github.com/dfinity/go-dfinity-crypto/bls.(*G2).HashAndMapTo(0xc4203843c0, 0xc4204d1380, 0x184, 0x1a0, 0x184, 0x1a0)
	/home/nalos/prog/go/src/github.com/dfinity/go-dfinity-crypto/bls/mcl.go:352 +0x60 fp=0xc4204872d8 sp=0xc420487278
github.com/dedis/paper_17_dfinity/pbc.(*pointG2).Base(0xc4203843c0, 0x184, 0xc4203843c0)
	/home/nalos/prog/go/src/github.com/dedis/paper_17_dfinity/pbc/point.go:148 +0x79 fp=0xc420487318 sp=0xc4204872d8
```

It may be the library, or may be Golang's cgo internal  or... I don't know ! 
Would you have any hints ?

Thanks a lot

Ps: you can find my tests [here](https://github.com/dedis/paper_17_dfinity/tree/master/protocol)

**Comment by nikkolasg** [comment]
Ok I find I have a clue why it happens. `TestDKGProtocol` uses 382_2 and `TestMarshalling` uses Fp254. Both tests are ran sequentially though, how is that possible... ? Seems like some field from one pairing are still there when I change the pairing or stg ?

**Comment by nikkolasg** [comment]
Yes that's it. Here's my test where I try to marshal and unmarshal a packet containing a point from G2. First time I try with the 382_2 pairing, then with the Fp254 **sequentially**.
Is it possible make it work somehow ? Seems like the old pairing is still stuck and causes the seg fault.
```go
p := pbc.NewPairingFp382_2()
	g2 := p.G2()
	msg := &PBCContext{
		Index:   0,
		Private: g2.NewKey(random.Stream),
	}
	msg.Roster = []abstract.Point{g2.Point().Mul(nil, msg.Private)}
	buff, err := protobuf.Encode(msg)
	require.Nil(t, err)
	decoded := &PBCContext{}
	require.Nil(t, decode(buff, decoded, g2))
	reflect.DeepEqual(decoded, msg)

	p = pbc.NewPairingFp254BNb()
	g2 = p.G2()
	msg = &PBCContext{
		Index:   0,
		Private: g2.NewKey(random.Stream),
	}
	msg.Roster = []abstract.Point{g2.Point().Mul(nil, msg.Private)}
	buff, err = protobuf.Encode(msg)
	require.Nil(t, err)
	decoded = &PBCContext{}
	require.Nil(t, decode(buff, decoded, g2))
	reflect.DeepEqual(decoded, msg)
```

**Comment by herumi** [comment]
Though I do not read your report in detail, there is one possibility of the error.

https://github.com/dfinity/bn/blob/master/bls/include/bls/bls.h#L52-L53
```
@note blsInit() is thread safe and serialized if it is called simultaneously
but don't call it while using other functions.
```

It will cause segmentation fault if some operation (for example, a destructor of cgo in defer or gc) of for Fp382_2 is called after blsInit for Fp254BNb.

**Comment by nikkolasg** [comment]
OK I see what you mean. I don't understand why I can't reproduce the error anymore. I'll try to see if I can force the GC before switching to a new pairing if it happens again. 
Thanks !

**Comment by herumi** [comment]
I see. I'll check it later.
